Update logs.tpl
I still have an error 500 with this file :

"  File "/var/lib/shinken/modules/webui2/plugins/logs/views/logs.tpl", line 133, in <module>
    %for log in records:
TypeError: 'NoneType' object is not iterable"

The "records" entry is missing in this template.

I modified it with adding the same "if loop" you did in the history.tpl (including the table class).

Now I can access to System/Logs.